language: node_js
node_js: node
cache:
  directories:
    - node_modules
#script:
#  - npm run lint
env:
  - CI=true

before_deploy:
  - npm install -g @vue/cli
  - npm install netlify-cli -g
  - npm run build
  - ls

deploy:
  provider: script
  script: netlify deploy --prod -s $NETLIFY_SITE_ID -a $NETLIFY_PUBLISH_KEY
  skip_cleanup: true
  on:
    branch: master