# example netlify.toml
[build]
  command = "npm run test:unit && npm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/api/v1/anagram/*"
  to = "https://anagramapi.rajatonit.com/api/v1/anagram/:splat"
  status = 200

## Uncomment to use this redirect for Single Page Applications. 
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


## more info https://www.netlify.com/docs/netlify-toml-reference/
